apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
  namespace: memoire-app
  labels:
    app: products-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: products-service
          image: ghcr.io/yvescape/products-service:fdaaf00
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: PRODUCTS_DATABASE_URL
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_PUBLIC_KEY
            - name: INTERNAL_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: INTERNAL_SERVICE_TOKEN
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10