apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce
  namespace: memoire-app
  labels:
    app: e-commerce
spec:
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: e-commerce
  template:
    metadata:
      labels:
        app: e-commerce
    spec:
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: e-commerce
          image: ghcr.io/yvescape/e-commerce:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10