apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce
  namespace: memoire-app
  labels:
    app: e-commerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-commerce
  template:
    metadata:
      labels:
        app: e-commerce
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: e-commerce
          image: ghcr.io/yvescape/e-commerce:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              value: "http://api.memoire.local"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10