apiVersion: v1
kind: Service
metadata:
  name: e-commerce
  namespace: memoire-app
  labels:
    app: e-commerce
spec:
  selector:
    app: e-commerce
  ports:
    - name: http
      port: 3000
      targetPort: 80
  type: ClusterIP