apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api-gateway
  namespace: memoire-app
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`api.memoire.local`)
      kind: Rule
      services:
        - name: api-gateway
          namespace: memoire-app
          kind: TraefikService
          port: 8080