apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: memoire-app

resources:
  - 00-namespace.yaml
  # secrets & config
  - sealed-secret.yaml
  # postgresql
  - postgres/configmap-init.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  # microservices
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - users-service/deployment.yaml
  - users-service/service.yaml
  - users-service/metric-templates.yaml
  - users-service/canary.yaml
  - products-service/deployment.yaml
  - products-service/service.yaml
  - orders-service/deployment.yaml
  - orders-service/service.yaml
  - payments-service/deployment.yaml
  - payments-service/service.yaml
  - review-service/deployment.yaml
  - review-service/service.yaml
  # frontends
  - e-commerce/deployment.yaml
  - e-commerce/service.yaml
  - e-commerce/service-gateway-alias.yaml
  - admin/deployment.yaml
  - admin/service.yaml
  # routing
  - ingress.yaml